import uuid
from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException, Query, Path
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from pydantic import BaseModel

from app.api.deps import get_current_user
from app.db.models.user import User
from app.service.agent.service import chat_with_agent, stream_chat_with_agent, abort_chat_session
from app.dependencies import get_db, BaseResponse
from app.crud import agent as agent_crud
from app.schemas.agent import AgentSession, AgentSessionCreate, AgentSessionUpdate, AgentMessage

router = APIRouter()

class ChatRequest(BaseModel):
    message: str
    session_id: str | None = None
    stream: bool = False
    connection_id: str | None = None
    model_name: str | None = None

class ChatResponse(BaseModel):
    response: str
    session_id: str

@router.post("/chat", summary="与智能相册助手对话")
def chat_endpoint(
    request: ChatRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    处理与 TrailSnap Agent 的对话请求。
    如果 session_id 未提供，将自动生成一个新的。
    """
    session_id = request.session_id or str(uuid.uuid4())
    
    # Ensure session exists
    session = agent_crud.get_session(db, session_id)
    if not session:
        session_create = AgentSessionCreate(
            id=uuid.UUID(session_id),
            title="New Chat",  # This could be generated by AI later
            status="active"
        )
        agent_crud.create_session(db, obj_in=session_create, user_id=current_user.id)

    try:
        if request.stream:
            # 返回流式响应
            return StreamingResponse(
                stream_chat_with_agent(
                    user_id=str(current_user.id),
                    session_id=session_id,
                    user_input=request.message,
                    db=db,
                    connection_id=request.connection_id,
                    model_name=request.model_name
                ),
                media_type="text/event-stream"
            )
        else:
            reply = chat_with_agent(
                user_id=str(current_user.id),
                session_id=session_id,
                user_input=request.message,
                db=db,
                connection_id=request.connection_id,
                model_name=request.model_name
            )
            return ChatResponse(response=reply, session_id=session_id)
    except ValueError as ve:
        # 捕获由于未配置 LLM 引起的异常
        raise HTTPException(status_code=400, detail=str(ve))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"内部错误: {str(e)}")

@router.post("/chat/{session_id}/abort", summary="终止流式对话")
def abort_chat(
    session_id: str = Path(..., description="The ID of the session to abort"),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    手动终止后台正在运行的指定 session_id 的 AI 响应生成流。
    """
    session = agent_crud.get_session(db, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
    if str(session.user_id) != str(current_user.id):
        raise HTTPException(status_code=403, detail="Not authorized to access this session")
        
    abort_chat_session(session_id)
    return {"message": "Chat stream abort signal sent"}

@router.get("/sessions", response_model=List[AgentSession], summary="获取所有会话")
def get_sessions(
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=100),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    获取当前用户的所有会话列表。
    """
    return agent_crud.get_sessions_by_user(db, user_id=current_user.id, skip=skip, limit=limit)

@router.post("/sessions", response_model=AgentSession, summary="创建新会话")
def create_session(
    session_in: AgentSessionCreate,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    创建一个新的对话会话。
    """
    return agent_crud.create_session(db, obj_in=session_in, user_id=current_user.id)

@router.delete("/sessions/{session_id}", summary="删除会话")
def delete_session(
    session_id: str = Path(..., description="The ID of the session to delete"),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    删除指定的会话及其所有消息。
    """
    session = agent_crud.get_session(db, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
    if str(session.user_id) != str(current_user.id):
        raise HTTPException(status_code=403, detail="Not authorized to delete this session")
        
    success = agent_crud.delete_session(db, session_id)
    if not success:
        raise HTTPException(status_code=500, detail="Failed to delete session")
    return {"message": "Session deleted successfully"}

@router.put("/sessions/{session_id}/pin", response_model=AgentSession, summary="置顶/取消置顶会话")
def pin_session(
    is_pinned: bool = Query(..., description="True to pin, False to unpin"),
    session_id: str = Path(..., description="The ID of the session"),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    置顶或取消置顶指定的会话。
    """
    session = agent_crud.get_session(db, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
    if str(session.user_id) != str(current_user.id):
        raise HTTPException(status_code=403, detail="Not authorized to modify this session")
        
    session_update = AgentSessionUpdate(is_pinned=is_pinned)
    return agent_crud.update_session(db, db_obj=session, obj_in=session_update)

@router.get("/sessions/{session_id}/messages", response_model=List[AgentMessage], summary="获取会话消息")
def get_session_messages(
    session_id: str = Path(..., description="The ID of the session"),
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    获取指定会话的所有消息。
    """
    session = agent_crud.get_session(db, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
    if str(session.user_id) != str(current_user.id):
        raise HTTPException(status_code=403, detail="Not authorized to view this session")
        
    return agent_crud.get_messages_by_session(db, session_id, skip=skip, limit=limit)

@router.delete("/messages", summary="删除会话的消息")
def delete_messages(
    session_id: str = Query(..., description="The ID of the session"),
    message_ids: str = Query(None, description="Comma-separated list of message IDs to delete"),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    删除指定会话的全部或部分消息。
    """
    session = agent_crud.get_session(db, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
    if str(session.user_id) != str(current_user.id):
        raise HTTPException(status_code=403, detail="Not authorized to modify this session")
        
    if message_ids:
        ids_list = [int(i.strip()) for i in message_ids.split(",") if i.strip().isdigit()]
        if ids_list:
            from app.db.models.agent import AgentMessage as DBAgentMessage
            db.query(DBAgentMessage).filter(
                DBAgentMessage.session_id == session.id,
                DBAgentMessage.id.in_(ids_list)
            ).delete(synchronize_session=False)
            db.commit()
    else:
        success = agent_crud.delete_messages_by_session(db, session_id)
    return {"message": "Messages deleted successfully"}

@router.get("/memory", summary="获取 AI 记住的长期记忆")
def get_memory(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    返回 AI 记住的、与当前用户相关的长期记忆锚点（照片即记忆）。
    返回前会自动校验每条记忆指向的照片仍然存在、归属正确且未被删除，失效项会被剔除。
    """
    from app.service.agent.memory import get_valid_memory_anchors
    anchors = get_valid_memory_anchors(db, str(current_user.id))
    return BaseResponse.success(data={"anchors": anchors})

@router.delete("/memory/{photo_id}", summary="删除一条长期记忆")
def delete_memory(
    photo_id: str = Path(..., description="要遗忘的记忆锚点对应的照片 ID"),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    删除指定照片对应的一条长期记忆，让 AI "遗忘"这段回忆。用户对自己的记忆有完全控制权。
    """
    from app.service.agent.memory import remove_memory_anchor
    removed = remove_memory_anchor(db, str(current_user.id), photo_id)
    if not removed:
        return BaseResponse.fail(code=404, msg="未找到对应的记忆")
    return BaseResponse.success(data={"photo_id": photo_id})

@router.get("/proactive", summary="获取未读的主动消息")
def get_proactive_messages(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """获取"那年今日"等主动关怀消息（未读）。用于侧边栏红点与打开助手时置顶展示。"""
    msgs = agent_crud.get_unread_proactive_messages(db, current_user.id)
    data = [
        {
            "id": m.id,
            "content": m.content,
            "anchor_date": (m.content_ext or {}).get("anchor_date"),
            "created_at": m.created_at,
        }
        for m in msgs
    ]
    return BaseResponse.success(data={"messages": data, "unread": len(data)})

@router.post("/proactive/{message_id}/read", summary="标记主动消息已读")
def read_proactive_message(
    message_id: int = Path(..., description="主动消息 ID"),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """把一条主动消息标记为已读，红点随之消失。"""
    ok = agent_crud.mark_proactive_read(db, current_user.id, message_id)
    if not ok:
        return BaseResponse.fail(code=404, msg="未找到对应的主动消息")
    return BaseResponse.success(data={"message_id": message_id})
