"""initial requirement platform

Revision ID: e2a3b299195e
Revises:
Create Date: 2026-09-08 19:56:50.308730
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e2a3b299195e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=40), nullable=False),
    sa.Column('object_id', sa.String(length=36), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_status'), ['status'], unique=False)
        batch_op.create_index('ix_jobs_status_available', ['status', 'available_at'], unique=False)

    op.create_table('github_webhook_events',
    sa.Column('delivery_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('delivery_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)
        batch_op.create_index('uq_users_single_owner', ['role'], unique=True, sqlite_where=sa.text("role = 'owner'"))

    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('object_type', sa.String(length=40), nullable=False),
    sa.Column('object_id', sa.String(length=36), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_object', ['object_type', 'object_id'], unique=False)

    op.create_table('release_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version_name', sa.String(length=50), nullable=False),
    sa.Column('batch_type', sa.String(length=24), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('target_date', sa.String(length=10), nullable=True),
    sa.Column('max_risk_level', sa.String(length=16), nullable=False),
    sa.Column('scope_summary', sa.Text(), nullable=True),
    sa.Column('github_milestone_number', sa.Integer(), nullable=True),
    sa.Column('github_milestone_url', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_milestone_number')
    )
    with op.batch_alter_table('release_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_release_batches_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_batches_version_name'), ['version_name'], unique=True)

    op.create_table('requirements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('current_behavior', sa.Text(), nullable=True),
    sa.Column('expected_behavior', sa.Text(), nullable=True),
    sa.Column('steps_to_reproduce', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('product_version', sa.String(length=50), nullable=True),
    sa.Column('environment', sa.JSON(), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('duplicate_of_id', sa.String(length=36), nullable=True),
    sa.Column('github_issue_number', sa.Integer(), nullable=True),
    sa.Column('github_issue_url', sa.String(length=500), nullable=True),
    sa.Column('github_state', sa.String(length=24), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['requirements.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_issue_number')
    )
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirements_created_by'), ['created_by'], unique=False)
        batch_op.create_index('ix_requirements_creator_status', ['created_by', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_status'), ['status'], unique=False)
        batch_op.create_index('ix_requirements_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_visibility'), ['visibility'], unique=False)

    op.create_table('release_batch_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('priority_order', sa.Integer(), nullable=False),
    sa.Column('delivery_status', sa.String(length=24), nullable=False),
    sa.Column('requirement_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['release_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'requirement_id', name='uq_batch_requirement')
    )
    with op.batch_alter_table('release_batch_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_release_batch_items_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_batch_items_requirement_id'), ['requirement_id'], unique=False)

    op.create_table('requirement_followers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requirement_id', 'user_id', name='uq_requirement_follower')
    )
    with op.batch_alter_table('requirement_followers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirement_followers_requirement_id'), ['requirement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirement_followers_user_id'), ['user_id'], unique=False)

    op.create_table('requirement_review_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requirement_review_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirement_review_decisions_requirement_id'), ['requirement_id'], unique=False)

    op.create_table('requirement_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('editor_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['editor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requirement_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirement_revisions_requirement_id'), ['requirement_id'], unique=False)

    op.create_table('triage_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('requirement_version', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('triage_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_triage_reports_requirement_id'), ['requirement_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('triage_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_triage_reports_requirement_id'))

    op.drop_table('triage_reports')
    with op.batch_alter_table('requirement_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirement_revisions_requirement_id'))

    op.drop_table('requirement_revisions')
    with op.batch_alter_table('requirement_review_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirement_review_decisions_requirement_id'))

    op.drop_table('requirement_review_decisions')
    with op.batch_alter_table('requirement_followers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirement_followers_user_id'))
        batch_op.drop_index(batch_op.f('ix_requirement_followers_requirement_id'))

    op.drop_table('requirement_followers')
    with op.batch_alter_table('release_batch_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_release_batch_items_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_release_batch_items_batch_id'))

    op.drop_table('release_batch_items')
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirements_visibility'))
        batch_op.drop_index(batch_op.f('ix_requirements_type'))
        batch_op.drop_index(batch_op.f('ix_requirements_title'))
        batch_op.drop_index('ix_requirements_status_created')
        batch_op.drop_index(batch_op.f('ix_requirements_status'))
        batch_op.drop_index('ix_requirements_creator_status')
        batch_op.drop_index(batch_op.f('ix_requirements_created_by'))

    op.drop_table('requirements')
    with op.batch_alter_table('release_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_release_batches_version_name'))
        batch_op.drop_index(batch_op.f('ix_release_batches_status'))

    op.drop_table('release_batches')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_object')

    op.drop_table('audit_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('uq_users_single_owner', sqlite_where=sa.text("role = 'owner'"))
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('github_webhook_events')
    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_status_available')
        batch_op.drop_index(batch_op.f('ix_background_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_object_id'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_job_type'))

    op.drop_table('background_jobs')
    # ### end Alembic commands ###
