"""Unit tests for the tag and face CRUD helpers (app.crud.tag + app.crud.face).

Covers pure-ORM / pure-Python helpers exposed by app.crud.tag and the
owner-aware identity helpers in app.crud.face. All database work is
replaced with ``MagicMock`` so no real Postgres is touched.

Generated by Nightly Watch 2026-08-12 round 8.
"""

from types import SimpleNamespace
from unittest.mock import MagicMock, patch
from uuid import uuid4

import pytest

from app.crud import face as crud_face
from app.crud import tag as crud_tag
from app.db.models.photo import FileType
from app.db.models.tag import PhotoTag
from app.schemas.face import FaceIdentityCreate, FaceUpdate
from app.schemas.photo import Photo as PhotoSchema
from app.schemas.tag import PhotoTagResponse, TagStats


pytestmark = [pytest.mark.smoke, pytest.mark.module_face]


_UNSET = object()


def _q(*, first=_UNSET, all=_UNSET, get=_UNSET):
    """Build a single SQLAlchemy ``query()`` mock with the common chains pre-wired.

    Covers chains seen across app.crud.tag and app.crud.face:

    - ``db.query(M).filter(...).first()``                                → first
    - ``db.query(M).filter(a).filter(b).first()``                       → first
    - ``db.query(M).filter(...).order_by(...).first()``                 → first
    - ``db.query(M).filter(a).filter(b).order_by(...).first()``         → first
    - ``db.query(M).filter(...).join(...).filter(...).first()``         → first
    - ``db.query(M).filter(...).all()``                                 → all
    - ``db.query(M).filter(a).filter(b).all()``                         → all
    - ``db.query(M).join(...).filter(...).all()``                       → all
    - ``db.query(M).join(...).filter(...).order_by(...).offset().limit().all()`` → all
    - ``db.query(M).get(pk)``                                           → get
    """
    m = MagicMock(name="q")
    if first is not _UNSET:
        # .filter().first()
        m.filter.return_value.first.return_value = first
        # .filter().filter().first()
        m.filter.return_value.filter.return_value.first.return_value = first
        # .filter().order_by().first()
        m.filter.return_value.order_by.return_value.first.return_value = first
        # .filter().filter().order_by().first()
        m.filter.return_value.filter.return_value.order_by.return_value.first.return_value = first
        # .filter().join().filter().first()
        m.filter.return_value.join.return_value.filter.return_value.first.return_value = first
        # .join().filter().first()
        m.join.return_value.filter.return_value.first.return_value = first
    if all is not _UNSET:
        # .filter().all()
        m.filter.return_value.all.return_value = all
        # .filter().filter().all()
        m.filter.return_value.filter.return_value.all.return_value = all
        # .join().filter().all()
        m.join.return_value.filter.return_value.all.return_value = all
        # .join().filter().order_by().offset().limit().all()
        m.join.return_value.filter.return_value.order_by.return_value.offset.return_value.limit.return_value.all.return_value = all
        # .join().outerjoin().filter().order_by().offset().limit().all()
        m.join.return_value.outerjoin.return_value.filter.return_value.order_by.return_value.offset.return_value.limit.return_value.all.return_value = all
        # .filter().offset().limit().all()
        m.filter.return_value.offset.return_value.limit.return_value.all.return_value = all
        # .filter().filter().offset().limit().all()
        m.filter.return_value.filter.return_value.offset.return_value.limit.return_value.all.return_value = all
        # .filter().order_by().offset().limit().all()
        m.filter.return_value.order_by.return_value.offset.return_value.limit.return_value.all.return_value = all
        # .filter().filter().order_by().offset().limit().all()
        m.filter.return_value.filter.return_value.order_by.return_value.offset.return_value.limit.return_value.all.return_value = all
    if get is not _UNSET:
        m.get.return_value = get
    return m


def _photo_schema(photo_id):
    """Build a Photo schema instance valid for TagStats.cover."""
    from datetime import datetime
    return PhotoSchema(
        id=photo_id,
        file_type=FileType.image,
        size=1024,
        width=100,
        height=100,
        duration=None,
        filename="test.jpg",
        photo_time=datetime(2026, 1, 1),
        file_path="/tmp/test.jpg",
        upload_time=datetime(2026, 1, 1),
    )

def _fresh_db():
    db = MagicMock(name="db")
    db.commit = MagicMock()
    db.add = MagicMock()
    db.delete = MagicMock()
    db.refresh = MagicMock()
    db.flush = MagicMock()
    return db


def _photo_schema(photo_id):
    """Build a Photo schema instance valid for TagStats.cover."""
    from datetime import datetime
    return PhotoSchema(
        id=photo_id,
        file_type=FileType.image,
        size=1024,
        width=100,
        height=100,
        duration=None,
        filename='test.jpg',
        photo_time=datetime(2026, 1, 1),
        file_path='/tmp/test.jpg',
        upload_time=datetime(2026, 1, 1),
    )


# =========================================================================
# app.crud.tag
# =========================================================================


def test_get_tag_by_name_returns_match_when_owner_provided():
    db = _fresh_db()
    db.query.return_value = _q(first="owned")

    result = crud_tag.get_tag_by_name(db, "summer", owner_id=uuid4())

    assert result == "owned"


def test_get_tag_by_name_returns_match_when_owner_is_none():
    db = _fresh_db()
    db.query.return_value = _q(first="public")

    result = crud_tag.get_tag_by_name(db, "shared", owner_id=None)

    assert result == "public"


def test_create_tag_persists_with_owner_and_type():
    db = _fresh_db()
    owner = uuid4()

    result = crud_tag.create_tag(db, "beach", tag_type="place", owner_id=owner)

    db.add.assert_called_once_with(result)
    db.commit.assert_called_once()
    db.refresh.assert_called_once_with(result)
    assert isinstance(result, PhotoTag)
    assert result.tag_name == "beach"
    assert result.type == "place"
    assert result.owner_id == owner


def test_create_tag_accepts_optional_type_and_owner():
    db = _fresh_db()

    result = crud_tag.create_tag(db, "untagged")

    assert result.tag_name == "untagged"
    assert result.type is None
    assert result.owner_id is None


def test_get_photo_tags_returns_responses_with_confidence():
    tag1 = SimpleNamespace(id=uuid4(), tag_name="beach")
    tag2 = SimpleNamespace(id=uuid4(), tag_name="summer")
    db = _fresh_db()
    db.query.return_value = _q(all=[(tag1, 0.95), (tag2, 0.75)])

    result = crud_tag.get_photo_tags(db, uuid4())

    assert len(result) == 2
    assert all(isinstance(item, PhotoTagResponse) for item in result)
    assert result[0].tag_name == "beach"
    assert result[0].confidence == 0.95
    assert result[1].confidence == 0.75


def test_add_tag_to_photo_creates_tag_when_missing():
    owner = uuid4()
    new_tag = SimpleNamespace(id=uuid4(), tag_name="fresh")
    db = _fresh_db()
    # First query: tag lookup → None; Second query: relation lookup → None.
    db.query.side_effect = [_q(first=None), _q(first=None)]

    with patch.object(crud_tag, "create_tag", return_value=new_tag) as create:
        result = crud_tag.add_tag_to_photo(
            db, uuid4(), "fresh", confidence=0.5, owner_id=owner,
        )

    create.assert_called_once_with(db, "fresh", "custom", owner)
    db.add.assert_called_once()  # relation added
    db.commit.assert_called_once()
    assert isinstance(result, PhotoTagResponse)
    assert result.tag_name == "fresh"
    assert result.confidence == 0.5


def test_add_tag_to_photo_revives_soft_deleted_relation():
    existing_tag = SimpleNamespace(id=uuid4(), tag_name="beach")
    relation = SimpleNamespace(is_deleted=True, confidence=0.1)
    db = _fresh_db()
    db.query.side_effect = [_q(first=existing_tag), _q(first=relation)]

    result = crud_tag.add_tag_to_photo(db, uuid4(), "beach", confidence=0.9)

    assert relation.is_deleted is False
    assert relation.confidence == 0.9
    assert result.confidence == 0.9


def test_add_tag_to_photo_keeps_existing_relation_when_not_deleted():
    existing_tag = SimpleNamespace(id=uuid4(), tag_name="beach")
    relation = SimpleNamespace(is_deleted=False, confidence=0.4)
    db = _fresh_db()
    db.query.side_effect = [_q(first=existing_tag), _q(first=relation)]

    crud_tag.add_tag_to_photo(db, uuid4(), "beach", confidence=0.4)

    # confidence 0.4 is not 1.0, so manual override branch is skipped
    assert relation.confidence == 0.4
    db.refresh.assert_called_once_with(relation)


def test_remove_tag_from_photo_deletes_when_relation_present():
    relation = SimpleNamespace()
    db = _fresh_db()
    db.query.return_value = _q(first=relation)

    crud_tag.remove_tag_from_photo(db, uuid4(), uuid4())

    db.delete.assert_called_once_with(relation)
    db.commit.assert_called_once()


def test_remove_tag_from_photo_returns_true_when_relation_missing():
    db = _fresh_db()
    db.query.return_value = _q(first=None)

    assert crud_tag.remove_tag_from_photo(db, uuid4(), uuid4()) is True
    db.delete.assert_not_called()


def test_remove_tags_from_photo_accepts_list():
    db = _fresh_db()
    db.query.return_value.filter.return_value.delete.return_value = 2

    result = crud_tag.remove_tags_from_photo(
        db, [uuid4(), uuid4()], ai_generated=True,
    )

    assert result is True
    db.commit.assert_called_once()


def test_get_tags_with_stats_attaches_cover_from_cover_id():
    tag_obj = SimpleNamespace(id=uuid4(), tag_name="beach", cover_id=uuid4())
    cover_photo = _photo_schema(tag_obj.cover_id)
    db = _fresh_db()
    # First query = subquery (no special return needed)
    # Second query = main result list.
    db.query.side_effect = [
        _q(),  # subquery
        _q(all=[(tag_obj, 3, cover_photo)]),  # main
    ]

    with patch.object(crud_tag, "desc", lambda col: col):
        result = crud_tag.get_tags_with_stats(db, uuid4(), skip=0, limit=10)

    assert len(result) == 1
    assert isinstance(result[0], TagStats)
    assert result[0].count == 3
    assert result[0].cover is cover_photo


def test_get_tags_with_stats_backfills_cover_when_missing():
    tag_obj = SimpleNamespace(id=uuid4(), tag_name="beach", cover_id=None)
    fallback = _photo_schema(uuid4())
    db = _fresh_db()
    db.query.side_effect = [
        _q(),                          # subquery
        _q(all=[(tag_obj, 2, None)]),  # main
        _q(first=fallback),            # backfill photo lookup
    ]

    with patch.object(crud_tag, "desc", lambda col: col):
        result = crud_tag.get_tags_with_stats(db, uuid4())

    assert tag_obj.cover_id == fallback.id
    db.commit.assert_called_once()
    assert result[0].cover is fallback


def test_get_photos_by_tag_name_returns_empty_when_tag_unknown():
    db = _fresh_db()
    db.query.return_value = _q(first=None)

    assert crud_tag.get_photos_by_tag_name(db, uuid4(), "ghost") == []


def test_get_photos_by_tag_name_returns_photos_ordered_by_time():
    tag_obj = SimpleNamespace(id=uuid4(), tag_name="beach")
    photos = [SimpleNamespace(id=uuid4()) for _ in range(3)]
    db = _fresh_db()
    db.query.side_effect = [
        _q(first=tag_obj),   # tag lookup
        _q(all=photos),      # photo lookup
    ]

    with patch.object(crud_tag, "desc", lambda col: col):
        result = crud_tag.get_photos_by_tag_name(db, uuid4(), "beach", skip=5, limit=20)

    assert result == photos


def test_remove_photos_from_tag_returns_zero_when_tag_missing():
    db = _fresh_db()
    db.query.return_value = _q(first=None)

    result = crud_tag.remove_photos_from_tag(db, uuid4(), "ghost", [uuid4()])

    assert result == 0
    db.commit.assert_not_called()


def test_remove_photos_from_tag_returns_delete_count():
    tag_obj = SimpleNamespace(id=uuid4(), tag_name="beach")
    db = _fresh_db()
    # Tag lookup → tag; delete chain → 4.
    db.query.return_value = _q(first=tag_obj)
    db.query.return_value.filter.return_value.delete.return_value = 4

    result = crud_tag.remove_photos_from_tag(db, uuid4(), "beach", [uuid4(), uuid4()])

    assert result == 4
    db.commit.assert_called_once()


def test_set_tag_cover_returns_false_when_tag_missing():
    db = _fresh_db()
    db.query.return_value = _q(first=None)

    assert crud_tag.set_tag_cover(db, uuid4(), "ghost", uuid4()) is False
    db.commit.assert_not_called()


def test_set_tag_cover_returns_false_when_photo_missing():
    tag_obj = SimpleNamespace(tag_name="beach")
    db = _fresh_db()
    db.query.side_effect = [_q(first=tag_obj), _q(first=None)]

    assert crud_tag.set_tag_cover(db, uuid4(), "beach", uuid4()) is False
    db.commit.assert_not_called()


def test_set_tag_cover_updates_cover_id_on_success():
    owner = uuid4()
    photo_id = uuid4()
    tag_obj = SimpleNamespace(tag_name="beach", cover_id=None)
    photo = SimpleNamespace(id=photo_id, owner_id=owner, is_deleted=False)
    db = _fresh_db()
    db.query.side_effect = [_q(first=tag_obj), _q(first=photo)]

    assert crud_tag.set_tag_cover(db, owner, "beach", photo_id) is True
    assert tag_obj.cover_id == photo_id
    db.commit.assert_called_once()


# =========================================================================
# app.crud.face
# =========================================================================


def _face(face_id=None, identity_id=None, is_deleted=False):
    return SimpleNamespace(
        id=face_id or 1,
        face_identity_id=identity_id,
        face_rect=[0, 0, 10, 10],
        face_confidence=0.9,
        recognize_confidence=0.8,
        face_feature=None,
        is_deleted=is_deleted,
        photo_id=uuid4(),
    )


def _identity(identity_id=None, owner_id=None, default_face_id=None, name="Alice"):
    return SimpleNamespace(
        id=identity_id or uuid4(),
        identity_name=name,
        owner_id=owner_id,
        default_face_id=default_face_id,
        is_deleted=False,
        create_time=None,
        update_time=None,
        description="",
        tags="",
        is_hidden=False,
    )


def test_get_face_with_owner_returns_owned_face():
    face = _face(face_id=1)
    db = _fresh_db()
    db.query.return_value = _q(first=face)

    result = crud_face.get_face(db, 1, owner_id=uuid4())

    assert result is face


def test_get_face_without_owner_returns_face():
    face = _face(face_id=1)
    db = _fresh_db()
    db.query.return_value = _q(first=face)

    result = crud_face.get_face(db, 1, owner_id=None)

    assert result is face


def test_update_face_returns_none_when_face_missing():
    db = _fresh_db()
    db.query.return_value = _q(first=None)

    result = crud_face.update_face(db, 1, FaceUpdate(), owner_id=uuid4())

    assert result is None
    db.commit.assert_not_called()


def test_update_face_sets_default_face_id_when_identity_has_none():
    identity = _identity(default_face_id=None)
    face = _face(face_id=42, identity_id=identity.id)
    db = _fresh_db()
    # First query: get_face → face. Second query: FaceIdentity.get(face.face_identity_id) → identity.
    db.query.side_effect = [
        _q(first=face),
        _q(get=identity),
    ]

    result = crud_face.update_face(db, 42, FaceUpdate(), owner_id=None)

    assert identity.default_face_id == 42
    db.commit.assert_called_once()
    db.refresh.assert_called_once()
    assert result is not None


def test_update_face_preserves_existing_default_face_id():
    existing = _face(face_id=99)
    identity = _identity(default_face_id=existing.id)
    face = _face(face_id=42, identity_id=identity.id)
    db = _fresh_db()
    db.query.side_effect = [
        _q(first=face),
        _q(get=identity),
    ]

    crud_face.update_face(db, 42, FaceUpdate())

    assert identity.default_face_id == existing.id


def test_create_identity_persists_owner_and_name():
    db = _fresh_db()
    owner = uuid4()

    result = crud_face.create_identity(
        db, FaceIdentityCreate(identity_name="Bob"), owner_id=owner,
    )

    db.add.assert_called_once_with(result)
    db.commit.assert_called_once()
    db.refresh.assert_called_once_with(result)
    assert result.identity_name == "Bob"
    assert result.owner_id == owner


def test_get_identities_with_owner_returns_list():
    db = _fresh_db()
    db.query.return_value = _q(all=[])

    result = crud_face.get_identities(db, skip=0, limit=5, owner_id=uuid4())

    assert result == []


def test_get_identities_without_owner_returns_list():
    db = _fresh_db()
    db.query.return_value = _q(all=[])

    result = crud_face.get_identities(db)

    assert result == []


def test_delete_face_returns_none_when_missing():
    db = _fresh_db()
    db.query.return_value = _q(first=None)

    assert crud_face.delete_face(db, 1, owner_id=uuid4()) is None
    db.commit.assert_not_called()


def test_delete_face_promotes_another_face_to_default():
    identity_id = uuid4()
    current_default = _face(face_id=1, identity_id=identity_id)
    other = _face(face_id=2, identity_id=identity_id)
    identity = _identity(identity_id=identity_id, default_face_id=1)
    db = _fresh_db()
    # 1) get_face → current_default
    # 2) db.query(FaceIdentity).get(face.face_identity_id) → identity
    # 3) db.query(Face).filter(...).order_by(...).first() → other
    db.query.side_effect = [
        _q(first=current_default),
        _q(get=identity),
        _q(first=other),
    ]

    result = crud_face.delete_face(db, 1, owner_id=None)

    assert result is current_default
    assert identity.default_face_id == 2
    db.delete.assert_called_once_with(current_default)
    db.commit.assert_called_once()


def test_delete_face_clears_default_when_no_other_face_exists():
    identity_id = uuid4()
    only = _face(face_id=1, identity_id=identity_id)
    identity = _identity(identity_id=identity_id, default_face_id=1)
    db = _fresh_db()
    db.query.side_effect = [
        _q(first=only),
        _q(get=identity),
        _q(first=None),
    ]

    crud_face.delete_face(db, 1)

    assert identity.default_face_id is None
    db.commit.assert_called_once()
