"""Unit tests for the pure-helper subset of crud.location_stats.

The pure helpers (`_haversine`, `_apply_date_filter`, `_travel_distance`)
are easy to test without SQLAlchemy chain mocking. The remaining functions
exercise long ORM chains (`get_overview`, `get_monthly_radar`) that are
covered indirectly via the e2e suite and the API smoke tests in
`test_nightly_api_gaps.py`.

Generated by Nightly Watch 2026-08-12 round 9.
"""

from types import SimpleNamespace
from unittest.mock import MagicMock

import pytest

from app.crud import location_stats as crud_ls


pytestmark = [pytest.mark.smoke]


# -------------------------------------------------------------------------
# _haversine
# -------------------------------------------------------------------------


def test_haversine_returns_zero_for_identical_points():
    assert crud_ls._haversine(30.5, 114.3, 30.5, 114.3) == 0


def test_haversine_matches_known_shanghai_to_beijing_distance():
    # Shanghai (31.2304, 121.4737) -> Beijing (39.9042, 116.4074) ~ 1067 km
    distance = crud_ls._haversine(31.2304, 121.4737, 39.9042, 116.4074)
    assert 1050 <= distance <= 1080


def test_haversine_symmetric_in_arguments():
    forward = crud_ls._haversine(31.2304, 121.4737, 39.9042, 116.4074)
    reverse = crud_ls._haversine(39.9042, 116.4074, 31.2304, 121.4737)
    assert abs(forward - reverse) < 0.01


# -------------------------------------------------------------------------
# _apply_date_filter
# -------------------------------------------------------------------------


def test_apply_date_filter_returns_query_unchanged_when_no_dates():
    query = MagicMock(name="query")

    result = crud_ls._apply_date_filter(query, None, None)

    assert result is query
    query.filter.assert_not_called()


def test_apply_date_filter_applies_start_date_only():
    query = MagicMock(name="query")
    after_filter = MagicMock(name="after_filter")
    query.filter.return_value = after_filter

    result = crud_ls._apply_date_filter(query, "2026-01-01", None)

    assert result is after_filter
    # One .filter() call carrying the start_date literal.
    query.filter.assert_called_once()
    bound = query.filter.call_args.args[0].right.value
    assert bound == "2026-01-01"


def test_apply_date_filter_applies_end_date_only():
    query = MagicMock(name="query")
    after_filter = MagicMock(name="after_filter")
    query.filter.return_value = after_filter

    result = crud_ls._apply_date_filter(query, None, "2026-12-31")

    assert result is after_filter
    query.filter.assert_called_once()
    bound = query.filter.call_args.args[0].right.value
    assert bound == "2026-12-31 23:59:59"


def test_apply_date_filter_chains_start_then_end():
    query = MagicMock(name="query")
    intermediate = MagicMock(name="intermediate")
    after_end = MagicMock(name="after_end")
    # query.filter() -> intermediate; intermediate.filter() -> after_end.
    query.filter.return_value = intermediate
    intermediate.filter.return_value = after_end

    result = crud_ls._apply_date_filter(query, "2026-01-01", "2026-12-31")

    assert result is after_end
    assert query.filter.call_count == 1
    assert intermediate.filter.call_count == 1


# -------------------------------------------------------------------------
# _travel_distance
# -------------------------------------------------------------------------


def test_travel_distance_returns_zero_for_no_rows():
    assert crud_ls._travel_distance([]) == 0


def test_travel_distance_returns_zero_for_single_centroid():
    rows = [SimpleNamespace(lat=30.5, lng=114.3)]
    assert crud_ls._travel_distance(rows) == 0


def test_travel_distance_skips_sub_kilometre_jitter():
    rows = [
        SimpleNamespace(lat=30.5000, lng=114.3000),
        SimpleNamespace(lat=30.5001, lng=114.3001),
    ]
    assert crud_ls._travel_distance(rows) == 0


def test_travel_distance_sums_multi_segment_journey():
    rows = [
        SimpleNamespace(lat=30.5000, lng=114.3000),  # Wuhan
        SimpleNamespace(lat=31.2304, lng=121.4737),  # Shanghai
        SimpleNamespace(lat=39.9042, lng=116.4074),  # Beijing
    ]
    total = crud_ls._travel_distance(rows)
    # Wuhan -> Shanghai + Shanghai -> Beijing > 1700 km.
    assert total > 1700


def test_travel_distance_handles_mixed_jitter_and_real_jump():
    rows = [
        SimpleNamespace(lat=30.5000, lng=114.3000),  # Wuhan
        SimpleNamespace(lat=30.5001, lng=114.3001),  # jitter, ignored
        SimpleNamespace(lat=31.2304, lng=121.4737),  # Shanghai
    ]
    total = crud_ls._travel_distance(rows)
    # Only Wuhan -> Shanghai counts; Shanghai distance ~ 689 km.
    assert 680 <= total <= 700
