"""add_daily_frames

Revision ID: sqlite_0017
Revises: sqlite_0016
Create Date: 2026-10-03 18:50:46.155756
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.types import UUID


revision: str = 'sqlite_0017'
down_revision: Union[str, Sequence[str], None] = 'sqlite_0016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_frame_calendars',
    sa.Column('owner_id', UUID(as_uuid=True), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('locked', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('owner_id')
    )
    op.create_table('daily_frame_works',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('owner_id', UUID(as_uuid=True), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('is_preview', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('task_id', UUID(as_uuid=True), nullable=True),
    sa.Column('processed_items', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('output_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'fingerprint', name='uq_daily_frame_work_fingerprint')
    )
    with op.batch_alter_table('daily_frame_works', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_frame_works_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_frame_works_owner_id'), ['owner_id'], unique=False)

    op.create_table('daily_frames',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('owner_id', UUID(as_uuid=True), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('photo_id', UUID(as_uuid=True), nullable=True),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('start_seconds', sa.Float(), nullable=False),
    sa.Column('caption', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('removed', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'day', name='uq_daily_frame_owner_day')
    )
    with op.batch_alter_table('daily_frames', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_frames_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_frames', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_frames_owner_id'))

    op.drop_table('daily_frames')
    with op.batch_alter_table('daily_frame_works', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_frame_works_owner_id'))
        batch_op.drop_index(batch_op.f('ix_daily_frame_works_created_at'))

    op.drop_table('daily_frame_works')
    op.drop_table('daily_frame_calendars')
    # ### end Alembic commands ###
