"""add_daily_frames

Revision ID: d1f139000001
Revises: a7c133000001
Create Date: 2026-10-03 18:50:44.875467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.types import UUID


# revision identifiers, used by Alembic.
revision: str = 'd1f139000001'
down_revision: Union[str, None] = 'a7c133000001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_frame_calendars',
    sa.Column('owner_id', UUID(as_uuid=True), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('locked', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('owner_id')
    )
    op.create_table('daily_frame_works',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('owner_id', UUID(as_uuid=True), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('is_preview', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('task_id', UUID(as_uuid=True), nullable=True),
    sa.Column('processed_items', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('output_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'fingerprint', name='uq_daily_frame_work_fingerprint')
    )
    op.create_index(op.f('ix_daily_frame_works_created_at'), 'daily_frame_works', ['created_at'], unique=False)
    op.create_index(op.f('ix_daily_frame_works_owner_id'), 'daily_frame_works', ['owner_id'], unique=False)
    op.create_table('daily_frames',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('owner_id', UUID(as_uuid=True), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('photo_id', UUID(as_uuid=True), nullable=True),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('start_seconds', sa.Float(), nullable=False),
    sa.Column('caption', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('removed', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'day', name='uq_daily_frame_owner_day')
    )
    op.create_index(op.f('ix_daily_frames_owner_id'), 'daily_frames', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_frames_owner_id'), table_name='daily_frames')
    op.drop_table('daily_frames')
    op.drop_index(op.f('ix_daily_frame_works_owner_id'), table_name='daily_frame_works')
    op.drop_index(op.f('ix_daily_frame_works_created_at'), table_name='daily_frame_works')
    op.drop_table('daily_frame_works')
    op.drop_table('daily_frame_calendars')
    # ### end Alembic commands ###
