<template><div ref="root" class="footprint-fallback" data-testid="footprint-fallback"><canvas ref="canvas" aria-label="足迹地图兼容视图" @click="pick" /><div class="fallback-badge">兼容地图 · 当前浏览器未启用 WebGL</div></div></template>
<script setup lang="ts">
import { onMounted, onBeforeUnmount, ref, watch } from 'vue'
import type { FootprintCity, FootprintRoute } from '@/types/footprint'
const props=defineProps<{cities:FootprintCity[];routes:FootprintRoute[];mode:'2d'|'3d'|'globe';layers:any;selectedCityId:string|null;activeRouteIndex:number;playing:boolean;rotating:boolean}>(); const emit=defineEmits<{ 'select-city':[id:string] }>(); const root=ref<HTMLElement>(); const canvas=ref<HTMLCanvasElement>(); let raf=0
function draw(){const el=canvas.value;if(!el)return;const w=el.clientWidth,h=el.clientHeight;if(!w||!h)return;const d=devicePixelRatio||1;el.width=w*d;el.height=h*d;const c=el.getContext('2d');if(!c)return;c.setTransform(d,0,0,d,0,0);c.clearRect(0,0,w,h);const cx=w*.47,cy=h*.52,r=Math.min(w*.34,h*.45);const g=c.createRadialGradient(cx-r*.3,cy-r*.3,10,cx,cy,r);g.addColorStop(0,'#194b73');g.addColorStop(1,'#020912');c.fillStyle=props.mode==='2d'?'#061a2d':g;c.beginPath();props.mode==='2d'?c.rect(0,0,w,h):c.arc(cx,cy,r,0,7);c.fill();const p=(x:number,y:number)=>[cx+(x-105)/55*r,cy-(y-32)/38*r] as [number,number];if(props.layers.routes)props.routes.forEach((q,i)=>{const a=p(q.from[0],q.from[1]),b=p(q.to[0],q.to[1]);c.strokeStyle=i===props.activeRouteIndex?'#ffd27a':'#ffb85688';c.lineWidth=i===props.activeRouteIndex?3:1.5;c.beginPath();c.moveTo(...a);c.quadraticCurveTo((a[0]+b[0])/2,(a[1]+b[1])/2-30,...b);c.stroke()});props.cities.forEach(x=>{const [a,b]=p(x.lng,x.lat);const s=x.id===props.selectedCityId?8:5;c.fillStyle='#35aaff';c.shadowColor='#35aaff';c.shadowBlur=18;c.beginPath();c.arc(a,b,s,0,7);c.fill();c.shadowBlur=0;c.fillStyle='#e5f4ff';c.font='12px sans-serif';c.fillText(x.name,a+9,b-8)});if(props.playing)raf=requestAnimationFrame(draw)}
function pick(e:MouseEvent){const el=canvas.value;if(!el)return;const r=el.getBoundingClientRect(),scale=Math.min(el.clientWidth*.34,el.clientHeight*.45);let hit:FootprintCity|undefined;let best=28;for(const x of props.cities){const [a,b]=[r.width*.47+(x.lng-105)/55*scale,r.height*.52-(x.lat-32)/38*scale];const z=Math.hypot(e.clientX-r.left-a,e.clientY-r.top-b);if(z<best){best=z;hit=x}}if(hit)emit('select-city',hit.id)}
onMounted(()=>{new ResizeObserver(draw).observe(root.value!);draw()});watch(()=>[props.cities,props.routes,props.mode,props.layers,props.selectedCityId,props.activeRouteIndex,props.playing],draw,{deep:true});onBeforeUnmount(()=>cancelAnimationFrame(raf))
</script><style scoped>.footprint-fallback,.footprint-fallback canvas{position:absolute;inset:0;width:100%;height:100%;background:#020810}.fallback-badge{position:absolute;left:18px;bottom:16px;color:#9ca3af;background:#071525d9;border:1px solid #29445d;border-radius:8px;padding:7px 10px;font-size:10px;pointer-events:none}</style>
